version: "3.9"

services:
  app:
    image: nikkoadr/ujian:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ujian
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      # hanya public storage (sesuai K8s)
      - ./storage/app/public:/app/storage/app/public
      - ./bootstrap/cache:/app/bootstrap/cache

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - ujian-net

networks:
  ujian-net:
    driver: bridge
